# Generated by Django 2.0.1 on 2018-02-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloP', models.CharField(max_length=140)),
                ('autorP', models.CharField(max_length=100)),
                ('contentP', models.TextField()),
                ('uploadDateTime', models.DateTimeField(auto_now=True)),
                ('fontImg', models.ImageField(upload_to='static/images')),
            ],
        ),
    ]
