# Generated by Django 2.0.1 on 2018-02-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloTut', models.CharField(max_length=250)),
                ('autorTut', models.CharField(max_length=140)),
                ('contenidoTut', models.TextField()),
                ('tutDateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
