# Generated by Django 2.0.1 on 2018-02-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoriales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedTutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloShort', models.CharField(max_length=100)),
                ('contenidoShort', models.CharField(max_length=140)),
                ('featuredImage', models.ImageField(upload_to='static/images')),
            ],
        ),
    ]
