# Generated by Django 2.0.1 on 2018-02-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180215_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='holo', max_length=150),
            preserve_default=False,
        ),
    ]
