# Generated by Django 2.0.1 on 2018-02-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180218_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedBlogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryId', models.IntegerField()),
                ('tituloShort', models.CharField(max_length=100)),
                ('contenidoShort', models.CharField(max_length=140)),
                ('featuredImage', models.ImageField(upload_to='blog/static/blog/images')),
            ],
        ),
    ]
