# Generated by Django 2.0.1 on 2018-02-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_featuredblogentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredblogentry',
            name='featuredImage',
            field=models.ImageField(upload_to='blog/images'),
        ),
    ]
