# Generated by Django 2.0.1 on 2018-02-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180220_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredblogentry',
            name='featuredImage',
            field=models.ImageField(upload_to='blog/static/blog/images'),
        ),
    ]
